[package]

name = "ex_listener"
version = "0.1.0"
authors = [ "jknightmmcs <jediknight.93@mail.ru>" ]

[[bin]]

name = "ex_listener"

[dependencies]
linux_tuples_client = { path = "../linux_tuples_client" }

