[package]

name = "ex_sender"
version = "0.1.0"
authors = [ "jknightmmcs <jediknight.93@mail.ru>" ]

[[bin]]

name = "ex_sender"

[dependencies]
linux_tuples_client = { path = "../linux_tuples_client" }
time = "0.1"
